version: 3
devices:
  - type: read.ok
    instances:
      - info: Reads data successfully
        data:
          id: 1
  - type: read.error
    instances:
      - info: Always fails reading
        data:
          id: 2
  - type: write.ok
    instances:
      - info: Writes data successfully
        data:
          id: 3
  - type: write.error
    instances:
      - info: Always fails writing
        data:
          id: 4
